### ISSUE TITLE
Conflict detected

### ISSUE THREAD

**Issue by Kame03** [hnhx/user.js#2]
When I try to add my own LibreX instance it gives me this: `Firefox could not install the search plugin from “https://search.milivojevic.in.rs/opensearch.xml?method=POST” because an engine with the same name already exists.`
but in search settings the remove button is greyed out I cannot remove your instance, I want to use the one I host because or geographical location, I think other users will also run into this error.

**Comment by hnhx** [comment]
Oh, I think thats because the name of the search engine is the same. Try renaming it in opensearch.xml and after that it should work.

Also you have to select another main search engine before you can remove it :P
